# Generated by Django 4.2.4 on 2023-08-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rooms_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
    ]
